services:
  imdb-api:
    build:
      context: .
    restart: "unless-stopped"
    env_file:
      - ./env/api.env
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./data/volume/api:/data
    depends_on:
      imdb-postgres:
        condition: service_healthy
  imdb-postgres:
    image: postgres:17  
    container_name: "imdb-postgres"
    restart: "unless-stopped"
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - ./env/pg.env
    volumes:   
      - ./data/volume/pg/data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s
    command: |
        -c min_wal_size=2GB
        -c max_wal_size=10GB
        -c checkpoint_completion_target=0.9
