services:
  imdb-api:
    image: ghcr.io/bbilly1/imdb-db
    container_name: "imdb-api"
    restart: "unless-stopped"
    environment:
      - DATABASE_URL=postgresql+asyncpg://imdb-db:secret123@imdb-postgres:5432/imdb-db
      - DATABASE_URL_SYNC=postgresql://imdb-db:secret123@imdb-postgres:5432/imdb-db
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./data/volume/api:/data
    depends_on:
      imdb-postgres:
        condition: service_healthy
  imdb-postgres:
    image: postgres:17  
    container_name: "imdb-postgres"
    restart: "unless-stopped"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=imdb-db
      - POSTGRES_PASSWORD=secret123
      - POSTGRES_DB=imdb-db
    volumes:   
      - ./data/volume/pg/data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s
    command: |
        -c min_wal_size=2GB
        -c max_wal_size=10GB
        -c checkpoint_completion_target=0.9
