services:
  imdb-postgres:
    image: postgres:17  
    container_name: "imdb-postgres"
    restart: "unless-stopped"
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - ./env/pg.env
    volumes:   
      - ./data/volume/pg/data:/var/lib/postgresql/data/
    command: |
        -c min_wal_size=2GB
        -c max_wal_size=10GB
        -c checkpoint_completion_target=0.9
